'use client';
import { useEffect, useState } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Card, CardContent } from '@/components/ui/card';
type Profile = { id:string; username:string; bio?:string|null; countryCode?:string|null; avatarUrl?:string|null };
const cloud = 'dnehlugrc'; const preset = 'geogame_avatars';
export default function ProfileClient({ userId }: { userId:string }) {
 const router=useRouter(); const {data:session}=useSession(); const me=(session?.user as any)?.id; const [profile,setProfile]=useState<Profile|null>(null); const [saving,setSaving]=useState(false);
 useEffect(()=>{ fetch(`/api/profile/${userId}`).then(r=>r.json()).then(setProfile); },[userId]); if(!profile)return <main className="p-10 text-center">Loading profile…</main>; const own=me===userId;
 const save=async()=>{setSaving(true);const r=await fetch(`/api/profile/${userId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)});if(r.ok){setProfile(await r.json());}else alert('Could not save profile');setSaving(false)};
 const upload=async(file:File)=>{const form=new FormData();form.append('file',file);form.append('upload_preset',preset);const r=await fetch(`https://api.cloudinary.com/v1_1/${cloud}/image/upload`,{method:'POST',body:form});const d=await r.json(); if(d.secure_url)setProfile({...profile,avatarUrl:d.secure_url});};
 const add=async()=>{const r=await fetch('/api/friends',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:profile.username})}); alert(r.ok?'Friend request sent':'Could not send request');};
 return <main className="min-h-screen bg-background p-6"><div className="max-w-xl mx-auto space-y-5"><Button variant="ghost" onClick={()=>router.back()}>← Back</Button><Card><CardContent className="p-8 space-y-5 text-center"><label className="block cursor-pointer"><img src={profile.avatarUrl||`https://ui-avatars.com/api/?name=${encodeURIComponent(profile.username)}&background=14b8a6&color=fff&size=200`} className="w-28 h-28 object-cover rounded-full mx-auto"/><input type="file" accept="image/*" className="hidden" disabled={!own} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/>{own&&<p className="text-xs text-muted-foreground mt-2">Click photo to change it</p>}</label>{own?<><Input value={profile.username} onChange={e=>setProfile({...profile,username:e.target.value})}/><Input placeholder="Country code, e.g. TN" maxLength={2} value={profile.countryCode||''} onChange={e=>setProfile({...profile,countryCode:e.target.value.toUpperCase()})}/><textarea className="w-full rounded-lg border bg-background p-3" maxLength={240} placeholder="Write a short bio" value={profile.bio||''} onChange={e=>setProfile({...profile,bio:e.target.value})}/><Button className="w-full" loading={saving} onClick={save}>Save profile</Button></>:<><h1 className="text-2xl font-bold">{profile.username} {profile.countryCode&&<span>{String.fromCodePoint(...[...profile.countryCode].map(c=>127397+c.charCodeAt(0)))}</span>}</h1><p className="text-muted-foreground">{profile.bio||'No bio yet.'}</p><Button onClick={add}>Add friend</Button></>}</CardContent></Card></div></main>;
}
